	<div class="thema_flex">
		<div class="thema_flex_text">
			<p>iPhoneやAndroidのスマホ画面には、アプリだけではなく<span class="line_marker" style="color:#c8161d;">WEBサイトの「ショートカットアイコン」を追加</span>することができます。
			<br><br>毎回検索して訪れるのではなく、アイコンとしてホーム画面に登録しましょう。アイコンを1回タップするだけで本サイトへアクセスできますので、とても便利でおススメです。
			<br><br>以下に登録方法を記載しておきますので、参考にしながらぜひ設定してみてください。</p>
			<br class="display_425px_off"><br class="display_425px_off"><h2>パソコンの設定について</h2>
			<p>パソコンに関しても同様ですが、本サイトのURLを<span class="line_marker" style="color:#c8161d;">ブックマーク・星マーク・リーディングリスト・お気に入り</span>のいずれかで登録してください。</p>
		</div>
		<div class="thema_flex_img">
			<img class="icon_yumekana" src="/neon/img/common/icon_128.png" alt="" />
			<img class="iphon_icon" src="/img/common/iphon.png" alt="" />
		</div>
	</div>
	<h2>iPhoneホーム画面への追加方法</h2>
	<div class="iPhone_text">
		<ol>
			<li>ブラウザ / safariでWEBページを開いた状態で下部のアイコンをタップします。<br>
			<span style="color: #c8161d">※グーグルChromeでは追加できませんので、必ずsafariで行ってください</span></li><br>
			<li>出てきたメニュー内の「ホーム画面に追加」をタップします。</li><br>
			<li>画面右上の「追加」をタップします。<br>
			※アイコンになる画像と、タイトルが出てきます。タイトルは短めに編集可能です。<br>
			※アイコンの設定がないサイトは、サイト表示をサムネイルにした画像が自動で設定されます。</li><br>
			<li>ホーム画面にアイコンが追加されます。</li>
		</ol>
		<div class="iPhone_img">
			<img src="/img/common/iphon_1.jpg" alt="" />
		</div>
	</div>
	<h2>Androidホーム画面への追加方法</h2>
		<div class="android_text">
		<ol>
			<li>標準ブラウザでホーム画面に追加したいWEBページを開き、ブックマークしてください。</li><br>
			<li>赤枠で囲ったブックマークアイコンをタップし、ブックマークしたページを長押しします。</li><br>
			<li>「ホーム画面に追加」をタップします。<br>
			※機種によっては「ショートカットを作成」と表示されます。</li><br>
			<li>ホーム画面にアイコンが追加されます<br>
			※ギャラクシーなどの機種によっては、ホーム画面に追加したいページを開き、<br>端末のメニューボタン（液晶画面の外にある）から直接追加できるものもあります。</li>
		</ol>
		<div class="android_img">
			<img src="/img/common/android_1.jpg" alt="" />
		</div>
	</div>