</div><!--main_body-->

<footer class="footer_667_none">
    <nav>
        <ul>
            <li><span>サービス紹介 <i class="fas fa-caret-down"></i></span>
                <ul>
                    <li><a href="/neon/service/live.php">LIVE</a></li>
                    <li><a href="/neon/service/archive.php">動画コンテンツ</a></li>
                    <li><a href="/neon/service/">1DAY講座</a></li>
                    <li><a href="/neon/service/salon.php">サロン会員募集</a></li>
                    <li><a href="/guide/">マーケットプレイス</a></li>
                </ul>
            </li>
            <li><span>サポート <i class="fas fa-caret-down"></i></span>
                <ul>
                    <li><a href="/neon/info/index.php">お知らせ</a></li>
                    <li><a href="/neon/config/">アイコン追加方法</a></li>
                    <li><a href="/neon/guide/qa.php">よくある質問</a></li>
                    <li><a href="/neon/contact/">お問い合わせ</a></li>
                </ul>
            </li>
            <li><span>運営情報 <i class="fas fa-caret-down"></i></span>
                <ul>
                    <li><a href="/neon/administrator/index.php">運営者情報</a></li>
                    <li><a href="/neon/rule/privacy.php">プライバシーポリシー</a></li>
                    <li><a href="/neon/rule/">利用規約</a></li>
                    <li><a href="/neon/guide/marketplace.php">NEON×夢を叶える百貨店</a></li>
                    <li><a href="/neon/law/">特定商取引法に基づく表記</a></li>
                </ul>
            </li>
            <li><a href="/neon/login/" class="header_login">新規登録・ログイン</a></li>
        </ul>
        <div class="nav_icon_footer">
            <div class="sns_kv_footer">
                
                <a href="https://www.instagram.com/moeko_tate0316/" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram fa-fw"></i></a>
                <a href="https://www.facebook.com/profile.php?id=100027498694185" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook-f fa-fw"></i></a>
                <a href="https://bit.ly/3OUBcqc" target="_blank" rel="noopener noreferrer"><i class="fab fa-line fa-fw"></i></a>
                <a href="https://profile.ameba.jp/ameba/moeko141066-23/" target="_blank" rel="noopener noreferrer"><i class="fas fa-blog fa-fw"></i></a>

                        <!-- <a href="" target="_blank" rel="noopener noreferrer"><i class="fab fa-youtube fa-fw"></i></a>
                        <a href="" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter fa-fw"></i></a> -->
            </div>
            <a href="/"><img src="/neon/img/common/neon_logo_kuro_300.png" alt="" /></a>
        </div>
    </nav>
</footer>
<div class="smp_footer_div">
    <p>&copy;2022 NEON</p>
</div>

</div>
</div>
</div>
</body></html>