	<input id="acd-check1" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check1">
			<span class="qa_question">Q１</span>
			<span class="qa_question_text">無料会員から有料会員にはなれますか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A１</span>
		  <span class="qa_answer_text">はい！もちろんなれます。下記リンクよりお申し込みください。<br>（有料会員へのリンク掲載）</span>
		</div></div>

	<input id="acd-check2" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check2">
			<span class="qa_question">Q２</span>
			<span class="qa_question_text">有料会員の申込みをしたいのですが、クレジットカード（デビットカード含む）がありません。銀行振り込みは対応していますか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A２</span>
		  <span class="qa_answer_text">はい！銀行振り込みご希望の場合は、下記フォームより申請をお願いします。フォームの確認ができ次第、振込先をご連絡させていただきます。<br><a href="/neon/contact/index.php"><u>お問い合わせはこちら</u></a></span>
		</div></div>

	<input id="acd-check3" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check3">
			<span class="qa_question">Q３</span>
			<span class="qa_question_text">リアルイベント（勉強会）などにも参加できるとのことですが、どこに案内はありますか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A３</span>
		  <span class="qa_answer_text">当サイトの「お知らせ」に随時掲載させていただきますので、そちらでご確認ください。<br><a href="/neon/info/index.php"><u>お知らせはこちら</u></a></span>
		</div></div>

	<input id="acd-check4" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check4">
			<span class="qa_question">Q４</span>
			<span class="qa_question_text">学びたいことがたくさんあります！講義内容のリクエストなどはできますか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A４</span>
		  <span class="qa_answer_text">積極的なお申し出は大歓迎です！下記問い合わせフォームよりリクエストください。<br><a href="/neon/contact/index.php"><u>お問い合わせはこちら</u></a></span>
		</div></div>

	<input id="acd-check5" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check5">
			<span class="qa_question">Q５</span>
			<span class="qa_question_text">もっと学びたい！場合、ビジネスコミュニティーNEON本会員にはなれますか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A５</span>
		  <span class="qa_answer_text">下記問い合わせフォームよりご連絡ください。<br><a href="/neon/contact/index.php"><u>お問い合わせはこちら</u></a><br>（有料会員へのリンク掲載）</span>
		</div></div>

	<input id="acd-check6" class="acd-check" type="checkbox">
		<label class="acd-label" for="acd-check6">
			<span class="qa_question">Q６</span>
			<span class="qa_question_text">諸事情により退会を希望する場合、どうすればいいですか？</span>
		</label>
		<div class="acd-content">
		<div class="inner">
		  <span class="qa_answer">A６</span>
		  <span class="qa_answer_text">下記フォームよりお手続きください。<br>（退会用のリンク掲載）</span>
		</div></div>




