<style type="text/css">body {background:#fff;}</style>

<div class="kv_service">
	<img class="display_567px_off" src="/neon/img/common/original.jpg" alt="" />
	<img class="display_567px_on" src="/neon/img/common/original2.jpg" alt="" />
</div>

<section class="section_neon_contain_960">
	<h2 class="section_h2_">こんなことに<br><span>悩</span>んでいませんか？</h2>

    <ul class="pera1_ul">
    	<li><span class="material-symbols-outlined">check</span><span class="span_">何から始めたら良いかわからない</span></li>
    	<li><span class="material-symbols-outlined">check</span>SNSを構築して<span class="span_">集客</span>ができるようになりたい</li>
    	<li><span class="material-symbols-outlined">check</span>自分の商品がなかなか<span class="span_">売れない</span></li>
    	<li><span class="material-symbols-outlined">check</span><span class="span_">自分の方向性がわからない</span>、定まらない</li>
    	<li><span class="material-symbols-outlined">check</span>頑張りたいのにモチベーションが<span class="span_">続かない</span></li>
    	<li><span class="material-symbols-outlined">check</span>わからないことが<span class="span_">解消されず</span>前に進めない</li>
    </ul>

	<div class="entry_btn">
		<a href="https://bit.ly/2ZQuD3A">講座はこちらから<span class="material-symbols-outlined">arrow_right</span></a>
	</div>

	<h2>SNSを使って集客できたら<br><span>時間や場所に捉われず</span><br>仕事ができるはずなのに・・</h2>
</section>
<section class="section_contain_style01">
	<div class="contents_area">
		<div class="contents_area_left">
			<img class="" src="/neon/img/common/original_2.jpg" alt="" />
		</div>
		<div class="contents_area_left">
        	<p>とにかく発信してみるものの、<br><span class="span_">成果を出せていない方がほとんどです</span>。<br><br>
        		女性は男性と比べて、<br>結婚・出産・育児などの環境の変化が激しいですよね。<br><br>
        		今まで通りに好きな仕事ができなくなったり、<br>収入が減ったり、自分の思い通りにいかず<br><br>
        		「こんなはずじゃなかったのに...」と<br><br>
        		我慢する・諦めるなど、「なんで女ばかり...」と<br><span class="span_">悔しい思い</span>をしたことはありませんか？<br><br>
        		でも本当は、<br><br>
        		「私だって自立して稼いでいきたい！」<br>「自分なりのキャリアを築いていきたい！」<br>「もっと自分に自信が欲しい！」<br><br>
        		という女性は多いはずです。<br><br>
        		<span class="span_">環境の変化に振り回されやすい女性だから</span>こそ、<br>SNSを使ってビジネスを構築することで<br><br>
        		時間も、場所も、働き方は<br>＼<span class="span_">アナタ自身で決める</span>／<br>ことができますよね</p>
		</div>
	</div>
</section>

<section class="section_contain_style02">
	<div class="inner">
		<h2><span>SNSで集客できない</span>のは<br>こんなことが原因かも</h2>
	    <ul class="pera1_ul_">
	    	<li><span class="material-symbols-outlined">check</span>SNSの仕組みを<span class="span_">理解できていない</span></li>
	    	<li><span class="material-symbols-outlined">check</span>相手に興味を持たれる文章が<span class="span_">書けていない</span></li>
	    	<li><span class="material-symbols-outlined">check</span>相手に<span class="span_">認知されていない</span></li>
	    	<li><span class="material-symbols-outlined">check</span><span class="span_">SNSマーケティング</span>ができていない</li>
	    	<li><span class="material-symbols-outlined">check</span><span class="span_">ブランディング</span>（見せ方）が整っていない</li>
	    </ul>
	</div>
</section>

<section class="section_neon_contain_960">
	<h2>SNSでの発信に<br><span>反応がない？</span></h2>
    <p class="pic_text">＼それってもしかして／</p>
</section>

<section class="section_contain_style03">
	<div class="contents_area_3">
		<p class="contents_area_p_title">SNSで闇雲に多くの人へ<br>発信していませんか？</p>
    	<p>SNSで集客をしてビジネスをしたい！なら<br class="display_425px_off">効果のある発信の仕方とその仕組みを理解し、<br class="display_425px_off">たった一人のお客様へ向けて<br class="display_425px_off">発信することが重要です。</p>
	</div>
</section>
<section class="section_neon_contain_960">
	<div class="entry_btn">
		<a href="https://bit.ly/2ZQuD3A">講座はこちらから<span class="material-symbols-outlined">arrow_right</span></a>
	</div>
</section>
<section class="section_contain_style02">
	<h2>SNS集客で外せない</span><br>4つのポイント</span></h2>
<div class="pic_4point">
	<div>
	    <div><img class="" src="/neon/img/common/original_000.png" alt="" /></div>
	    <p class="pic_title">拡散力</p>
	    <p>SNSを見てもらうための行動をして「いいね」を取ることで<span>あなたの発信が多くの方に拡散されます</span></p>
	</div>
	<div>
	    <div><img src="/neon/img/common/original_001.png" alt="" /></div>
	    <p class="pic_title">認知</p>
	    <p>ビジネスをしていく上で「認知」されなければ選択肢に入ることができません。そのための<span>マーケティングが必要不可欠です</span></p>
	</div>
	<div>
	    <div><img src="/neon/img/common/original_002.png" alt="" /></div>
	    <p class="pic_title">ブランディング</p>
	    <p>見せ方の工夫は他の人や商品との<span>「差別化」</span>です。ブランディングができないとあなたが選ばれることは難しくなります</p>
	</div>
	<div>
	    <div><img src="/neon/img/common/original_003.png" alt="" /></div>
	    <p class="pic_title">ファン化</p>
	    <p>影響力を持つことによってあなたは興味を持たれます。ファンができることで<span>営業することなく集客もセールスも可能</span>です</p>
	</div>
 </div>
</section>

<section class="section_neon_contain_960">
<h2>SNSビジネスコンプリート<br>1day講座は<br>こんな方へおすすめ</h2>
</section>

<section class="section_contain_style01">
	<div class="contents_area_4">
		<div class="contents_area_left_4">
			<img class="" src="/neon/img/common/original_3.png" alt="" />
		</div>
		<div class="contents_area_right_4">
 			<ul class="pera1_ul_4">
		    	<li><span class="material-symbols-outlined">check</span><span class="span_">未経験</span>でも<span class="span_">稼げるスキル</span>を身につけたい</li>
		    	<li><span class="material-symbols-outlined">check</span>SNSの<span class="span_">仕組み</span>を知りたい</li>
		    	<li><span class="material-symbols-outlined">check</span>SNSで<span class="span_">集客できるようになりたい</span></li>
		    	<li><span class="material-symbols-outlined">check</span><span class="span_">効果のある発信方法</span>が知りたい</li>
		    	<li><span class="material-symbols-outlined">check</span><span class="span_">ファンビジネス</span>興味がある</li>
		    	<li><span class="material-symbols-outlined">check</span>今の自分に<span class="span_">必要なものを知りたい</span></li>
		    </ul>
		</div>
	</div>
</section>

<section class="section_neon_contain_960 mt90px">
	<h2>コンサルティング<br>・・MENU・・</h2>
	<div class="c_menu_box">
		<div class="c_menu_box_left">
		    <div class="menu_nam">Menu<span class="">1</span></div>
		    <div class="menu_title">ターゲットの明確化</div>
		    <p class="menu_text">最も大切なのはターゲット。あなたの商品を必要としている方を徹底的に設定します。</p>
		</div>
		<div class="c_menu_box_right">
			<img class="" src="/neon/img/common/original_004.png" alt="" />
		</div>
	</div>

	<div class="c_menu_box c_menu_box_r">
		<div class="c_menu_box_left_">
			<img class="" src="/neon/img/common/original_005.png" alt="" />
		</div>
		<div class="c_menu_box_right_">
			<div class="menu_nam">Menu<span class="">2</span></div>
		    <div class="menu_title">魅了するライティング</div>
		    <p class="menu_text">ターゲット決定後、相手に響く文章を書きます。書き方、構成にも大切なポイントがあります。</p>
		</div>
	</div>

	<div class="c_menu_box">
		<div class="c_menu_box_left">
		    <div class="menu_nam">Menu<span class="">3</span></div>
		    <div class="menu_title">影響力アップのSNS構築</div>
		    <p class="menu_text">SNSには影響力が必要です。「拡散力」を上げるために多くの「いいね」が取れる方法を伝授します。</p>
		</div>
		<div class="c_menu_box_right">
			<img class="" src="/neon/img/common/original_001.png" alt="" />
		</div>
	</div>

	<div class="c_menu_box c_menu_box_r">
		<div class="c_menu_box_left_">
			<img class="" src="/neon/img/common/original_006.png" alt="" />
		</div>
		<div class="c_menu_box_right_">
			<div class="menu_nam">Menu<span class="">4</span></div>
		    <div class="menu_title">ブランディング戦略</div>
		    <p class="menu_text">「魅せ方」「世界観」構築で差別化していきます。反応の取れる写真の撮り方を、徹底構築します。</p>
		</div>
	</div>

	<div class="c_menu_box">
		<div class="c_menu_box_left">
		    <div class="menu_nam">Menu<span class="">5</span></div>
		    <div class="menu_title">公式LINE構築＆運用法</div>
		    <p class="menu_text">興味を持った方をLINEへ誘導します。効果的な運用方法で「欲しい」と言われる構築法を伝授します。</p>
		</div>
		<div class="c_menu_box_right">
			<img class="" src="/neon/img/common/original_007.png" alt="" />
		</div>
	</div>

	<div class="c_menu_box c_menu_box_r">
		<div class="c_menu_box_left_">
			<img class="" src="/neon/img/common/original_000.png" alt="" />
		</div>
		<div class="c_menu_box_right_">
			<div class="menu_nam">Menu<span class="">6</span></div>
		    <div class="menu_title">コンサルティング力</div>
		    <p class="menu_text">あなたのビジネスをより繁栄させるための「サポートの秘訣」も伝授します。</p>
		</div>
	</div>
</section>

<section class="section_contain_style02">
<h2>SNSビジネスコンプリート<br>1Day講座<br><br>・・詳細・・</h2>
<div class="table_box">
	<table>
	    <tr>
	        <th>日時</th>
	        <td>お申し込み後、個別に日程を決定いたします</td>
	    </tr>
	    <tr>
	        <th>参加料金</th>
	        <td>¥5,000 (税込）</td>
	    </tr>
	</table>
</div>
</section>

<section class="section_neon_contain_960">
	<div class="entry_btn">
		<a href="https://bit.ly/2ZQuD3A">講座はこちらから<span class="material-symbols-outlined">arrow_right</span></a>
	</div>
</section>

<section class="section_neon_contain_960 mb80px">
	<h2>・・Q＆A・・</h2>
	<table class="table_qa">
	    <tr>
	        <th><span>Q</span></th>
	        <td class="bold">全くの初心者ですが、大丈夫ですか？</td>
	    </tr>
	    <tr>
	        <th><span class="answer">A</span></th>
	        <td>はい、もちろん大丈夫です。パソコンも持ってなかった方もいらっしゃいます。また、初心者の方でもすぐに使えるテンプレート等もご用意しておりますので、順番にスキルを身につけならがら実践していくことができます。</td>
	    </tr>
	    <tr>
	        <th><span>Q</span></th>
	        <td class="bold">セミナーの所要時間を教えてください</td>
	    </tr>
	    <tr>
	        <th><span class="answer">A</span></th>
	        <td>あなたの今の疑問について、１つ１つアドバイスをしていきますので約2〜2.5時間いただいております。</td>
	    </tr>
	    <tr>
	        <th><span>Q</span></th>
	        <td class="bold">オンラインセミナーも可能でしょうか？</td>
	    </tr>
	    <tr>
	        <th><span class="answer">A</span></th>
	        <td>もちろん対応しています。無料で使えるZOOMを活用しますので、スマホやタブレットでも受講可能です。但し、画面が小さいのでパソコンで受けることを推奨しています。</td>
	    </tr>
	    <tr>
	        <th><span>Q</span></th>
	        <td class="bold">今まで学んだことを活かすことはできますか？</td>
	    </tr>
	    <tr>
	        <th><span class="answer">A</span></th>
	        <td>もちろん可能です！自分でビジネスをしていく上で努力は裏切りません。あなたのスキル、得意なこと、これからやりたいことを商品にする方法までサポートしていますので安心してお越しください。</td>
	    </tr>
	</table>

</section>