<style type="text/css">.main>div {background-color: #f8f8f8!important;}</style>
<div class="sticky_area">
<div class="sticky_area_inner">
    <div class="sticky_area_right display_menu"><!-- サポートメニュー -->
        <p class="pankuzu"><span>NEON</span><span>サポート</span></p>
        <div class="sticky_area_right_inner">
            <ul>
                <li><a id="info__" href="/neon/info/index.php">お知らせ</a></li>
                <li><a id="config__" href="/neon/config/">アイコン追加方法</a></li>
                <li><a id="qa__" href="/neon/guide/qa.php">よくある質問</a></li>
                <li><a id="contact__" href="/neon/contact/">お問い合わせ</a></li>
                <li><a id="administrator__" href="/neon/administrator/index.php">運営者情報</a></li>
                <li><a id="privacy__" href="/neon/rule/privacy.php">プライバシーポリシー</a></li>
            </ul>
            <ul class="mt10px">
                <li><a id="marketplace__" href="/neon/guide/marketplace.php">NEON × 夢を叶える百貨店</a></li>
            </ul>
        </div>
    </div>
    <div class="sticky_area_right display_rule"><!-- 利用規約メニュー -->
        <p class="pankuzu"><span>NEON</span><span>利用規約</span></p>
        <div class="sticky_area_right_inner">
            <ul>
                <li><a id="rule__" href="/neon/rule/index.php">NEON 利用規約</a></li>
                <li><a id="paid__" href="/neon/rule/paid.php">NEON 有料利用規約</a></li>
            </ul>
            <ul class="mt10px">
                <li><a id="privacy__" href="/neon/rule/privacy_.php">プライバシーポリシー</a></li>
            </ul>
        </div>
    </div>
    <div class="sticky_area_left"><!-- メイン表示 -->