</div>

<footer class="footer_667_none">
    <nav>
        <ul>
            <li><span>フロアマップ <i class="fas fa-caret-down"></i></span>
                <ul>
                    <li><a href="/item/index.php">1F フリーマーケット</a></li>
                    <li><a href="/item/index_s.php">2F スキルマーケット</a></li>
                    <li><a href="/course/index.php">3F ムービーマーケット</a></li>
                    <li><a href="/seminar/index.php">4F イベントマーケット</a></li>
                    <li class="li_listing"><a href="/guide/market.php">フロアガイド</a></li>
                </ul>
            </li>
            <li><span>総合案内 <i class="fas fa-caret-down"></i></span>
                <ul>
                <li><a href="/information/">総合案内</a></li>
                    <li><a href="/guide/archive.php">ご利用ガイド</a></li>
                    <li><a href="/guide/access.php">アクセス方法</a></li>
                    <li><a href="/contact/">お問い合わせ</a></li>
                </ul>
            </li>
            <li><span>運営情報 <i class="fas fa-caret-down"></i></span>
                <ul>
                    <li><a href="/company/">運営会社概要</a></li>
                    <li><a href="/rule/privacy.php">プライバシーポリシー</a></li>
                    <li><li><a href="/rule/">利用規約</a></li></li>
                    <li><a href="/law/">特定商取引に関する表記</a></li>
                </ul>
            </li>
            <li><a href="/login/" class="header_login">新規登録・ログイン</a></li>
        </ul>
        <div class="nav_icon">
            <div class="nav_icon_inner">
                <a href="https://lin.ee/j1c4rBK" target="_blank" rel="noopener noreferrer"><i class="fab fa-line fa-fw"></i></a>
            </div>
            <a href="/"><img src="/img/common/yumewokanaeru_logo_A_line.png" alt="" /></a>
        </div>
    </nav>
</footer>
<div class="smp_footer_div">
	<p>&copy;2022 夢を叶える百貨店</p>
</div>

</div>
</div>
</div>
</body></html>